// automatically generated by the FlatBuffers compiler, do not modify

package com.jk.greeter;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
final public class Greeter {

  static { System.loadLibrary("Greeter"); }

  public static HelloReply sayHello(String message) {
    FlatBufferBuilder builder = new FlatBufferBuilder();
    builder.finish(HelloRequest.createHelloRequest(builder, builder.createString(message)));
    byte[] reply = _sayHello(builder.sizedByteArray());
    return HelloReply.getRootAsHelloReply(ByteBuffer.wrap(reply));
  }
  public static PlayResult play(String path) {
    FlatBufferBuilder builder = new FlatBufferBuilder(0);
    builder.finish(PlayRequest.createPlayRequest(builder, builder.createString(path)));
    byte[] reply = _play(builder.dataBuffer().array());
    return PlayResult.getRootAsPlayResult(ByteBuffer.wrap(reply));
  }
  private static native byte[] _sayHello(byte[] req);
  private static native byte[] _play(byte[] req);
}

