// automatically generated by the FlatBuffers compiler, do not modify

package com.jk.greeter;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayResult extends Table {
  public static PlayResult getRootAsPlayResult(ByteBuffer _bb) { return getRootAsPlayResult(_bb, new PlayResult()); }
  public static PlayResult getRootAsPlayResult(ByteBuffer _bb, PlayResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int err() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String msg() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createPlayResult(FlatBufferBuilder builder,
      int err,
      int msgOffset) {
    builder.startObject(2);
    PlayResult.addMsg(builder, msgOffset);
    PlayResult.addErr(builder, err);
    return PlayResult.endPlayResult(builder);
  }

  public static void startPlayResult(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addErr(FlatBufferBuilder builder, int err) { builder.addInt(0, err, 0); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(1, msgOffset, 0); }
  public static int endPlayResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

