LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := Greeter
LOCAL_SRC_FILES := hello_jni.cpp
LOCAL_C_INCLUDES := .
LOCAL_CFLAGS :=
LOCAL_LDFLAGS := -llog
LOCAL_SHARED_LIBRARIES :=
LOCAL_STATIC_LIBRARIES :=
include $(BUILD_SHARED_LIBRARY)
