// automatically generated by the FlatBuffers compiler, do not modify

package com.jk.greeter;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class HelloReply extends Table {
  public static HelloReply getRootAsHelloReply(ByteBuffer _bb) { return getRootAsHelloReply(_bb, new HelloReply()); }
  public static HelloReply getRootAsHelloReply(ByteBuffer _bb, HelloReply obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public HelloReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String message() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createHelloReply(FlatBufferBuilder builder,
      int messageOffset) {
    builder.startObject(1);
    HelloReply.addMessage(builder, messageOffset);
    return HelloReply.endHelloReply(builder);
  }

  public static void startHelloReply(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(0, messageOffset, 0); }
  public static int endHelloReply(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

