// automatically generated by the FlatBuffers compiler, do not modify

package com.github.jekinchen.flatjni;

import java.nio.*;
import java.lang.*;
import java.util.*;
import android.support.annotation.Nullable;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Greeter {
  static { System.loadLibrary("Greeter"); }

  @Nullable
  public static HelloReply hello(String name) {
    FlatBufferBuilder builder = new FlatBufferBuilder();
    builder.finish(HelloRequest.createHelloRequest(builder, name == null? 0 : builder.createString(name)));
    byte[] reply = _hello(builder.sizedByteArray());
    if (reply == null) return null;
    return HelloReply.getRootAsHelloReply(ByteBuffer.wrap(reply));
  }

  @Nullable
  public static SumResult sum(int i, int j) {
    FlatBufferBuilder builder = new FlatBufferBuilder();
    builder.finish(SumParam.createSumParam(builder, i, j));
    byte[] reply = _sum(builder.sizedByteArray());
    if (reply == null) return null;
    return SumResult.getRootAsSumResult(ByteBuffer.wrap(reply));
  }

  private static native byte[] _hello(byte[] req);
  private static native byte[] _sum(byte[] req);
}

