// automatically generated by the FlatBuffers compiler, do not modify

package com.github.jekinchen.flatjni;

import java.nio.*;
import java.lang.*;
import java.util.*;
import android.support.annotation.Nullable;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SumParam extends Table {
  public static SumParam getRootAsSumParam(ByteBuffer _bb) { return getRootAsSumParam(_bb, new SumParam()); }
  public static SumParam getRootAsSumParam(ByteBuffer _bb, SumParam obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SumParam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int i() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int j() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSumParam(FlatBufferBuilder builder,
      int i,
      int j) {
    builder.startObject(2);
    SumParam.addJ(builder, j);
    SumParam.addI(builder, i);
    return SumParam.endSumParam(builder);
  }

  public static void startSumParam(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addI(FlatBufferBuilder builder, int i) { builder.addInt(0, i, 0); }
  public static void addJ(FlatBufferBuilder builder, int j) { builder.addInt(1, j, 0); }
  public static int endSumParam(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

