// automatically generated by the FlatBuffers compiler, do not modify

package com.github.jekinchen.flatjni;

import java.nio.*;
import java.lang.*;
import java.util.*;
import android.support.annotation.Nullable;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SumResult extends Table {
  public static SumResult getRootAsSumResult(ByteBuffer _bb) { return getRootAsSumResult(_bb, new SumResult()); }
  public static SumResult getRootAsSumResult(ByteBuffer _bb, SumResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SumResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int result() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSumResult(FlatBufferBuilder builder,
      int result) {
    builder.startObject(1);
    SumResult.addResult(builder, result);
    return SumResult.endSumResult(builder);
  }

  public static void startSumResult(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addResult(FlatBufferBuilder builder, int result) { builder.addInt(0, result, 0); }
  public static int endSumResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

